// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WizaKonsulPLACOWKA.Data;

namespace WizaKonsulPLACOWKA.Migrations
{
    [DbContext(typeof(WizaKonsulPLACOWKAContext))]
    partial class WizaKonsulPLACOWKAContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WizaKonsulPLACOWKA.Models.Sprawa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdresKlienta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Decyzja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImieKlienta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazwiskoKlienta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NrDokumentuKlienta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tresc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypDokumentuKlienta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZdjecieKlienta")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sprawa");
                });
#pragma warning restore 612, 618
        }
    }
}
